In [1]:

import numpy as np
import pandas as pd


In [23]:
def wind_dir_prova_ale(u,v,azimuth,model):
    # --- Set the wind components based on the anemometer model ---
    # Based on the model, adjust the wind components (u, v) to align with the LEC system.
    if model == "RM_YOUNG_81000":
        u_LEC = -u   # Reverse the direction of the u component
        v_LEC = -v   # Reverse the direction of the v component
    elif model == "CAMPBELL_CSAT3":
        u_LEC = v    # Swap the u and v components
        v_LEC = -u   # Reverse the direction of the u component

    wind_direction = (np.degrees(np.arctan2(u_LEC, v_LEC)) + azimuth + 180) % 360

    return wind_direction

In [24]:
def wind_dir_prova_samuel(u,v,azimuth,model):
    # --- Set the wind components based on the anemometer model ---
    # Based on the model, adjust the wind components (u, v) to align with the LEC system.
    if model == "RM_YOUNG_81000":
        u_LEC = -u   # Reverse the direction of the u component
        v_LEC = -v   # Reverse the direction of the v component
    elif model == "CAMPBELL_CSAT3":
        u_LEC = v    # Swap the u and v components
        v_LEC = -u   # Reverse the direction of the u component

    wind_direction = (- np.degrees(np.arctan2(v_LEC, u_LEC)) + 270 + azimuth) % 360
    return wind_direction

In [ ]:
# casistiche:
# A
# azimuth acuto (30°) | vento da N-E (40°)<=> I quadrante
# azimuth acuto (30°) | vento da S-E (180-40=140) <=> II quadrante
# azimuth acuto (30°) | vento da S-W (180+40=220) <=> III quadrante
# azimuth acuto (30°) | vento da N-W (270+40=310) <=> IV quandrante


azimuth = 30
u_measured_LEC_rot = np.array([-np.sin(np.deg2rad(40-30)),
                               -np.cos(np.deg2rad(90-40-30)),
                               np.sin(np.deg2rad(40-30)),
                               np.cos(np.deg2rad(40-30))
                       ])
v_measured_LEC_rot = np.array([-np.cos(np.deg2rad(40-30)),
                               np.sin(np.deg2rad(90-40-30)),
                               np.cos(np.deg2rad(40-30)),
                               -np.sin(np.deg2rad(40-30))
                      ])
u_measured_Y = - u_measured_LEC_rot
v_measured_Y = - v_measured_LEC_rot
wind_dir_expected = [40, 140, 220, 310]


[ 40. 140. 220. 310.]
[ 40. 140. 220. 310.]


In [35]:

# D
# azimuth ottuso (120°) | vento da N-E (40°)<=> I quadrante
# azimuth ottuso (120°) | vento da S-E (180-40=140) <=> II quadrante
# azimuth ottuso (120°) | vento da S-W (180+40=220) <=> III quadrante
# azimuth ottuso (120°) | vento da N-W (270+40=310) <=> IV quandrante
azimuth = 120
u_measured_LEC_rot = np.array([np.cos(np.deg2rad(40-30)),
                               -np.sin(np.deg2rad(20)),
                               -np.cos(np.deg2rad(40-30)),
                               np.sin(np.deg2rad(40-30))
                       ])
v_measured_LEC_rot = np.array([-np.sin(np.deg2rad(40-30)),
                               -np.cos(np.deg2rad(20)),
                               np.sin(np.deg2rad(40-30)),
                               np.cos(np.deg2rad(40-30))
                               
                      ])
u_measured_Y = - u_measured_LEC_rot
v_measured_Y = - v_measured_LEC_rot
wind_dir_expected = [40, 140, 220, 310]
wind_dir_result_ale = wind_dir_prova_ale(u_measured_Y,v_measured_Y,azimuth,model="RM_YOUNG_81000")
print(wind_dir_result_ale)
wind_dir_result_samuel = wind_dir_prova_samuel(u_measured_Y,v_measured_Y,azimuth,model="RM_YOUNG_81000")
print(wind_dir_result_samuel)

[ 40. 140. 220. 310.]
[ 40. 140. 220. 310.]
